### ISSUE TITLE
Detect locale from browser/HTTP request (after session, before default configured)

### ISSUE THREAD

**Issue by brestows** [drmuey/p5-Dancer2-Plugin-Locale#5]
Hi :) 
How plugin determines which display the translation?
```
ls locale/
-rw-r--r-- 1 devcode users 1.1K Jan  2 19:21 en.json
-rw-r--r-- 1 devcode users 1.5K Jan  2 18:46 ru.json
```
Settings in config.yml
```
plugins:
    Ajax:
        content_type: 'application/json'
    Locales:
        default_locale: en
```
HTTP_ACCEPT_LANGUAGE in my browser : ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4

But the plugin always used  en.json
